export const APP__SET_LOADING = 'APP__SET_LOADING';
export const SET_PROFILE_ROOT = 'SET_PROFILE_ROOT';

// Auth
export const SET_AUTH_LOADER = 'SET_AUTH_LOADER';
export const UPDATE_LOGIN_USER = 'UPDATE_LOGIN_USER';
export const CLEAR_LOGIN_USER = 'CLEAR_LOGIN_USER';

export const UPDATE_SIGNIN_USER = `UPDATE_SIGNIN_USER`;
export const CLEAR_SIGNIN_USER = `CLEAR_SIGNIN_USER`;

export const UPDATE_SIGNUP_USER = `UPDATE_SIGNUP_USER`;
export const CLEAR_SIGNUP_USER = `CLEAR_SIGNUP_USER`;

export const UPDATE_ONBOARDING_USER = `UPDATE_ONBOARDING_USER`;
export const CLEAR_ONBOARDING_USER = `CLEAR_ONBOARDING_USER`;
export const SET_CHILD_ITEM = `SET_CHILD_ITEM`;
export const UPDATE_CHILD_ITEM = `UPDATE_CHILD_ITEM`;
export const CLEAR_CHILD_ITEM = `CLEAR_CHILD_ITEM`;

//User
export const SET_USER_LOADER = 'SET_USER_LOADER';
export const SET_USER_DATA = 'SET_USER_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';

//Child
export const SET_CHILD_LOADER = 'SET_CHILD_LOADER';
export const SET_CURRENT_CHILD = `SET_CURRENT_CHILD`;

export const SET_CHILD_LIST = `SET_CHILD_LIST`;
export const ADD_CHILD = `ADD_CHILD_DATA`;
export const DELETE_CHILD = `DELETE_CHILD_DATA`;
export const UPDATE_CHILD = 'UPDATE_CHILD_DATA';

export const SET_CHILD_DATA = 'SET_CHILD_DATA';
export const UPDATE_CHILD_DATA = 'UPDATE_CHILD_DATA';
export const CLEAR_CHILD_DATA = 'CLEAR_CHILD_DATA';

//Article
export const SET_ARTICLE_LOADER = 'SET_ARTICLE_LOADER';
export const SET_ARTICLE_LIST = `SET_ARTICLE_LIST`;
export const SET_FILTER_ARTICLE_LIST = `SET_FILTER_ARTICLE_LIST`;
export const SET_FEATURED_ARTICLE_LIST = `SET_FEATURED_ARTICLE_LIST`;

//Article Tag
export const SET_ARTICLE_TAG_LIST = `SET_ARTICLE_TAG_LIST`;

//Activity
export const SET_ACTIVITY_LOADER = `SET_ACTIVITY_LOADER`;
export const SET_ACTIVITY_LIST = `SET_ACTIVITY_LIST`;
export const SET_JUST_ADDED_ACTIVITY_LIST = `SET_JUST_ADDED_ACTIVITY_LIST`;
export const SET_FILTER_ACTIVITY_LIST = `SET_FILTER_ACTIVITY_LIST`;
export const SET_THEME_ACTIVITY_LIST = `SET_THEME_ACTIVITY_LIST`;
export const SET_ACTIVITY_ITEM = `SET_ACTIVITY_ITEM`;
export const SET_MILESTONE_TASK_ACTIVITY_LIST = `SET_MILESTONE_TASK_ACTIVITY_LIST`;
export const SET_CHILD_ACTIVITY_LIST = `SET_CHILD_ACTIVITY_LIST`;
export const SET_TODAY_ACTIVITY_LIST = `SET_TODAY_ACTIVITY_LIST`;

//Completed Activity
export const SET_COMPLETED_ACTIVITY_LOADER = `SET_COMPLETED_ACTIVITY_LOADER`;
export const SET_COMPLETED_ACTIVITY_LIST = `SET_COMPLETED_ACTIVITY_LIST`;
export const ADD_COMPLETED_ACTIVITY = `ADD_COMPLETED_ACTIVITY`;
export const UPDATE_COMPLETED_ACTIVITY = `UPDATE_COMPLETED_ACTIVITY`;
export const SET_TOTAL_COMPLETED_ACTIVITY = `SET_TOTAL_COMPLETED_ACTIVITY`;
export const SET_TOTAL_COMPLETED_ACTIVITY_THIS_MONTH = `SET_TOTAL_COMPLETED_ACTIVITY_THIS_MONTH`;

export const SET_COMPLETED_ACTIVITY_IMAGE_LIST = `SET_COMPLETED_ACTIVITY_IMAGE_LIST`;
export const SET_SORTED_COMPLETED_ACTIVITY_LIST = `SET_SORTED_COMPLETED_ACTIVITY_LIST`;

export const ADD_COMPLETED_ACTIVITY_IMAGE = `ADD_COMPLETED_ACTIVITY_IMAGE`;
export const DELETE_COMPLETED_ACTIVITY_IMAGE = `DELETE_COMPLETED_ACTIVITY_IMAGE`;

//Favorite Activity
export const SET_FAVORITE_ACTIVITY_LOADER = `SET_FAVORITE_ACTIVITY_LOADER`;
export const SET_FAVORITE_ACTIVITY_LIST = `SET_FAVORITE_ACTIVITY_LIST`;
export const SET_FAVORITE_ACTIVITY = `SET_FAVORITE_ACTIVITY`;
export const CLEAR_FAVORITE_ACTIVITY = `CLEAR_FAVORITE_ACTIVITY`;
export const UPDATE_FAVORITE_ACTIVITY = `UPDATE_FAVORITE_ACTIVITY`;

//Subject
export const SET_SUBJECT_LOADER = `SET_SUBJECT_LOADER`;
export const SET_SUBJECT_LIST = `SET_SUBJECT_LIST`;
export const UPDATE_SUBJECT = `UPDATE_SUBJECT`;

//Theme
export const SET_THEME_LOADER = `SET_THEME_LOADER`;
export const SET_THEME_LIST = `SET_THEME_LIST`;
export const SET_FEATURED_THEME_LIST = `SET_FEATURED_THEME_LIST`;

//Age
export const SET_AGE_LIST = `SET_AGE_LIST`;
export const UPDATE_AGE = `UPDATE_AGE`;

//Type of Activity
export const SET_TYPE_OF_ACTIVITY_LIST = `SET_TYPE_OF_ACTIVITY_LIST`;
export const UPDATE_TYPE_OF_ACTIVITY = `UPDATE_TYPE_OF_ACTIVITY`;

//Milestone
export const SET_MILESTONE_TASK_LOADER = `SET_MILESTONE_TASK_LOADER`;
export const SET_CURRENT_MILESTONE = `SET_CURRENT_MILESTONE`;
export const SET_MILESTONE_TASK_LIST = `SET_MILESTONE_TASK_LIST`;
export const UPDATE_MILETONE_TASK_LIST = `UPDATE_MILETONE_TASK_LIST`;
export const SET_MILESTONE_TASK = `SET_MILESTONE_TASK`;
export const UPDATE_MILESTONE_TASK = `UPDATE_MILESTONE_TASK`;
export const SET_CHILD_MILESTONE_TASK_LIST = `SET_CHILD_MILESTONE_TASK_LIST`;

export const SET_MILESTONE_LIST = `SET_MILESTONE_LIST`;

//Mindful Playtime

export const SET_MINDFUL_PLAYTIME_LOADER = `SET_MINDFUL_PLAYTIME_LOADER`;
export const SET_MINDFUL_PLAYTIME_LIST = `SET_MINDFUL_PLAYTIME_LIST`;
export const SET_TOTAL_MINDFUL_PLAYTIME = `SET_TOTAL_MINDFUL_PLAYTIME`;
export const SET_TOTAL_MINDFUL_PLAYTIME_THIS_MONTH = `SET_TOTAL_MINDFUL_PLAYTIME_THIS_MONTH`;
export const SET_STREAK_OF_THIS_MONTH = `SET_STREAK_OF_THIS_MONTH`;
export const SET_STREAK_OF_ALL_TIME = `SET_STREAK_OF_ALL_TIME`;

//  Quote List
export const SET_QUOTE_LOADER = `SET_QUOTE_LOADER`;
export const SET_QUOTE_LIST = `SET_QUOTE_LIST`;
