import { Platform, StyleSheet } from 'react-native';
import { WIN_HEIGHT, WIN_WIDTH } from '../../constants/constant';
import { colors } from '../../styles';
import { borderWidth, doubleIndent, halfindent, indent, lessIndent } from '../../styles/dimensions';
import Typography from '../../styles/Typography';
import { scale, scaleVertical } from '../../utils/scale';

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.white,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: indent,
  },
  rowList: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  imgDp: {
    width: 35,
    height: 35,
    borderRadius: 50,
  },
  headerTextWrap: {
    marginLeft: lessIndent,
  },
  headerText: {
    color: colors.black,
    fontFamily: 'NewSpirit-Regular',
    lineHeight: 22,
  },
  profileIcon: {
    marginLeft: halfindent,
    borderRadius: 50,
    position: 'relative',
    zIndex: 50,
  },
  modalName: {
    color: colors.black,
    fontFamily: 'NewSpirit-Regular',
    lineHeight: 25,
    fontSize: 20,
  },
  modalMonth: {
    color: colors.greylite,
    fontFamily: 'NewSpirit-Regular',
    fontSize: 15,
  },
  imgProfile: {
    width: 42,
    height: 42,
    borderRadius: 50,
  },
  cildMonth: {
    color: colors.greylite,
    fontFamily: 'NewSpirit-Regular',
  },
  rightHeadView: {
    width: 48,
    height: 48,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: indent,
    borderWidth: 1,
    borderColor: colors.circleBorder,
  },
  rootpadding: {
    padding: indent,
  },
  firstWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  centerWrap: {
    alignItems: 'center',
    alignSelf: 'center',
  },
  milestoneText: {
    color: colors.textPrimary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontFamily: 'Navigo-Medium',
    textAlign: 'center',
    fontSize: 10,
    lineHeight: 14,
  },
  yearText: {
    fontSize: 26,
    lineHeight: 33,
    fontFamily: 'NewSpirit-Regular',
    color: colors.black,
    textAlign: 'center',
  },
  cardDetails: {
    backgroundColor: colors.yellowcm,
    padding: indent,
    marginVertical: indent,
    borderRadius: 8,
  },
  cardText: {
    fontFamily: 'Navigo-Regular',
    color: colors.black,
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 22,
  },
  bmborder: {
    borderBottomWidth: 1,
    borderBottomColor: colors.primary,
    alignSelf: 'center',
  },
  chartText: {
    textAlign: 'center',
    color: colors.primary,
    fontFamily: 'Navigo-Regular',
    textTransform: 'uppercase',
    letterSpacing: 1.6,
  },
  cardWrap: {
    marginHorizontal: indent,
  },
  cardShadow: {
    shadowColor: colors.milesbox,
    shadowOffset: {
      width: 0,
      height: 9,
    },
    shadowOpacity: 0.5,
    shadowRadius: 12.35,
    elevation: 11,
    marginBottom: indent,
    borderRadius: 8,
    ...Platform.select({
      ios: {
        shadowColor: colors.milesbox,
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowOpacity: 0.23,
        shadowRadius: 2.62,

        elevation: 2,
        borderRadius: 8,
      },
    }),
  },
  cardRow: {
    paddingVertical: indent,
    paddingHorizontal: lessIndent,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardRowTwo: {
    paddingVertical: indent,
    paddingHorizontal: lessIndent,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardHead: {
    fontSize: 20,
    fontFamily: 'NewSpirit-Regular',
    color: colors.textColor,
    letterSpacing: 0.16,
  },
  taskWrapValue: {
    backgroundColor: colors.bgtask,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    marginLeft: lessIndent,
    paddingHorizontal: halfindent,
    paddingVertical: 4,
  },

  leftCardWrap: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  value: {
    color: colors.black,
    fontFamily: 'Navigo-Regular',
    letterSpacing: 1.6,
    marginRight: halfindent / 2,
  },
  rowTask: {
    flexDirection: 'row',
    padding: lessIndent,
    overflow: 'hidden',
  },
  rowTaskActive: {
    flexDirection: 'row',
    padding: lessIndent,
    backgroundColor: colors.splacebg,
    overflow: 'hidden',
  },
  selectTik: {
    marginTop: 2,
  },
  taskText: {
    fontFamily: 'Navigo-Regular',
    color: colors.darkGrey,
    width: 284,
    marginLeft: lessIndent,
  },
  earlyQuotes: {
    marginTop: lessIndent,
    marginBottom: indent,
  },
  earlyCard: {
    backgroundColor: colors.rootbg,
    borderRadius: 8,
    paddingVertical: doubleIndent + halfindent,
    paddingHorizontal: indent + halfindent,
  },
  logoImg: {
    alignSelf: 'center',
    width: 55,
    height: 55,
    marginBottom: lessIndent,
  },
  earlyText: {
    fontFamily: 'Navigo-Regular',
    textAlign: 'center',
    color: colors.textColor,
    alignSelf: 'center',
    lineHeight: 22,
  },
  //Modal
  modal: {
    backgroundColor: colors.transparent,
    flex: 1,
    justifyContent: 'flex-end',
  },
  keyBord: {
    flex: 1,
  },
  modalWrapper: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.transparent,
  },
  closeModal: {
    flex: 1,
  },
  rectView: {
    width: 50,
    height: 5,
    alignSelf: 'center',
    backgroundColor: colors.backgroundColor,
    opacity: 0.8,
    borderRadius: 25,
    marginBottom: scaleVertical(8),
  },
  modalBox: {
    justifyContent: 'flex-end',
    backgroundColor: colors.white,
    borderTopLeftRadius: lessIndent,
    borderTopRightRadius: lessIndent,
    position: 'relative',
    maxHeight: WIN_HEIGHT - scale(85),
  },
  modalBoxTwo: {
    justifyContent: 'flex-end',
    backgroundColor: colors.white,
    borderTopLeftRadius: lessIndent,
    borderTopRightRadius: lessIndent,
    position: 'relative',
    minHeight: WIN_HEIGHT - scale(80),
    maxHeight: WIN_HEIGHT - scale(80),
    ...Platform.select({
      ios: {
        maxHeight: WIN_HEIGHT - scale(115),
        minHeight: WIN_HEIGHT - scale(115),
      },
    }),
  },
  rowProfile: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: colors.borderColor,
    padding: indent,
  },
  addChildView: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: indent,
  },
  nameView: {
    marginLeft: indent + halfindent,
  },
  iconView: {
    width: 42,
    height: 42,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderRadius: 50,
    borderColor: colors.borderColor,
    alignItems: 'center',
    justifyContent: 'center',
  },
  //MilestoneModal
  milesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: indent,
    paddingVertical: indent,
    borderBottomWidth: 1,
    borderColor: colors.borderColor,
  },
  headMilesTone: {
    fontSize: 10,
    fontFamily: 'Navigo-Medium',
    color: colors.textPrimary,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  topWrapModal: {
    paddingVertical: indent + 2,
    paddingHorizontal: indent,
  },
  WrapLabel: {
    backgroundColor: colors.cream,
    alignSelf: 'center',
    paddingHorizontal: lessIndent,
    paddingVertical: halfindent / 2,
    borderRadius: 34,
    marginBottom: indent,
  },
  labelWrap: {
    fontSize: 10,
    lineHeight: 14,
    textTransform: 'uppercase',
    color: colors.black,
    letterSpacing: 1,
    fontFamily: 'Navigo-Medium',
  },
  noticeCaps: {
    textAlign: 'center',
    fontFamily: 'NewSpirit-Regular',
    letterSpacing: 0.16,
    color: colors.black,
  },
  btnWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginHorizontal: -6,
    marginTop: doubleIndent,
  },
  btnView: {
    flex: 0.5,
    marginHorizontal: halfindent - 2,
    overflow: 'hidden',
    borderRadius: 56,
  },
  btnStyle: {
    backgroundColor: colors.btnSecond,
  },
  btnText: {
    fontFamily: 'Navigo-Regular',
    color: colors.primary,
    ...Typography.bodyHead,
  },
  activityWrap: {
    marginTop: doubleIndent,
    backgroundColor: colors.rootbg,
    borderRadius: 8,
    paddingVertical: doubleIndent,
    paddingHorizontal: indent,
  },
  activityImg: {
    width: 40,
    height: 40,
    alignSelf: 'center',
  },
  recActivity: {
    textTransform: 'uppercase',
    fontFamily: 'Navigo-Medium',
    fontSize: 12,
    textAlign: 'center',
    marginTop: indent + 2,
    color: colors.textPrimary,
    letterSpacing: 1.2,
  },
  NoteText: {
    color: colors.textColor,
    fontFamily: 'Navigo-Regular',
    textAlign: 'center',
    marginTop: lessIndent,
    lineHeight: 22,
  },
  recommedWrap: {
    marginTop: doubleIndent,
    borderTopWidth: 1,
    borderColor: colors.borderColor,
  },
  activityText: {
    fontFamily: 'NewSpirit-Regular',
    color: colors.textColor,
    textAlign: 'center',
    marginTop: indent + halfindent,
  },
  //card Row
  cardList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: lessIndent,
    margin: -8,
  },
  rowcards: {
    width: '100%',
    maxWidth: '50%',
    minWidth: '50%',
    flex: 1,
    padding: halfindent,
  },
  cardItem: {
    paddingBottom: 12,
  },
  imgView: {
    backgroundColor: colors.bgimg,
    borderRadius: 8,
    overflow: 'hidden',
  },
  ImgList: {
    width: '100%',
    height: 160,
    borderRadius: 8,
  },
  darkText: {
    fontFamily: 'NewSpirit-Regular',
    color: colors.black,
    marginTop: halfindent,
    lineHeight: 19,
  },
  //popup Mdoal
  PopupModal: {
    width: 170,
    shadowColor: colors.black,
    overflow: 'hidden',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
    height: 'auto',
    borderRadius: 8,
    left: '20%',
    top: WIN_HEIGHT + lessIndent - scale(doubleIndent * 22),
  },
  imgPopup: {
    width: 26,
    height: 26,
    borderRadius: 100,
  },
  nameChild: {
    fontFamily: 'NewSpirit-Regular',
    color: colors.black,
    lineHeight: 15,
    marginLeft: halfindent,
  },
  firstRow: {
    paddingVertical: halfindent,
    paddingHorizontal: indent,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: borderWidth,
    borderColor: colors.popborder,
  },
  linkWrap: {
    marginTop: indent + halfindent,
    borderBottomWidth: 1,
    borderColor: colors.primary,
    alignSelf: 'center',
  },
  concerWrap: {
    paddingHorizontal: indent,
  },
  concerText: {
    color: colors.primary,
    textTransform: 'uppercase',
    ...Typography.caps,
    textAlign: 'center',
    letterSpacing: 1,
    fontFamily: 'Navigo-Medium',
  },
  TitleHead: {
    fontFamily: 'NewSpirit-Regular',
    fontSize: 30,
    lineHeight: 38,
    letterSpacing: 0.3,
    color: colors.textColor,
    marginTop: doubleIndent + 11,
    textAlign: 'center',
  },
  blogView: {
    marginTop: indent + halfindent,
  },
  blogCaps: {
    fontFamily: 'Navigo-Regular',
    fontSize: 16,
    lineHeight: 26,
    color: colors.textColor,
  },
  secondBlog: {
    marginTop: indent,
  },
  blogQues: {
    fontFamily: 'Navigo-Bold',
    fontSize: 16,
    lineHeight: 26,
    color: colors.textColor,
  },
  listWrap: {
    marginTop: indent,
    marginBottom: doubleIndent,
  },
  rowWrap: {
    flexDirection: 'row',
    // alignItems: 'center',
  },
  dotView: {
    width: 4,
    height: 4,
    backgroundColor: colors.textColor,
    borderRadius: 50,
    marginRight: lessIndent - 2,
    marginTop: 12,
  },
  listCaps: {
    fontFamily: 'Navigo-Regular',
    fontSize: 16,
    lineHeight: 26,
    color: colors.textColor,
  },
  selectIconActivity: {
    position: 'absolute',
    top: 6,
    left: 6,
  },
  mindfulModal: {
    width: WIN_WIDTH - indent * 3,
    height: 'auto',
    backgroundColor: colors.rootbg,
    borderRadius: 8,
  },
  wrapModal: {
    width: WIN_WIDTH - indent * 3,
    height: 'auto',
    backgroundColor: colors.bgstep,
    borderRadius: 8,
  },
  modalRoot: {
    paddingTop: doubleIndent,
    paddingBottom: indent + halfindent,
  },
  modalImg: {
    width: 129,
    height: 95,
    alignSelf: 'center',
  },
  titleModal: {
    fontFamily: 'NewSpirit-Regular',
    textAlign: 'center',
    marginTop: 15,
    letterSpacing: 0.24,
    color: colors.textColor,
  },
  modalBlog: {
    paddingHorizontal: indent,
  },
  modalcaps: {
    textAlign: 'center',
    marginTop: indent,
    fontFamily: 'Navigo-Regular',
    color: colors.textColor,
  },
  gotBtn: {
    marginTop: indent + halfindent,
  },
  closeIcon: {
    position: 'absolute',
    width: 40,
    height: 40,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
    right: 16,
    top: 16,
  },
});
