export default {
  Splash: 'Splash',
  Login: 'Login',
  Signup: 'Signup',
  ForgotPassword: 'ForgotPassword',
  OnBoarding: 'OnBoarding',
  NavigationRoot: 'NavigationRoot',
  HomeRoot: 'HomeRoot',
  Home: 'Home',
  ActivitiesRoot: 'ActivitiesRoot',
  Activities: 'Activities',
  MilestonesRoot: 'MilestonesRoot',
  Milestones: 'Milestones',
  ProfileRoot: 'ProfileRoot',
  Profile: 'Profile',
  MoreRoot: 'MoreRoot',
  More: 'More',
  AddChild: 'AddChild',
  SingleActivity: 'SingleActivity',
  SingleMilestones: 'SingleMilestones',
  ParentsProfile: 'ParentsProfile',
  KidsProfile: 'KidsProfile',
  AddChilds: 'AddChilds',
  CompleteProfile: 'CompleteProfile',
  TryEarlybird: 'TryEarlybird',
  Notifications: 'Notifications',
  Articles: 'Articles',
  ArticlesDetail: 'ArticlesDetail',
  ExploreActivities: 'ExploreActivities',
  ActivitiesTheme: 'ActivitiesTheme',
  SingleActivitySimple: 'SingleActivitySimple',
  ActivityComplete: 'ActivityComplete',
  CreatePassword: 'CreatePassword',
  PlayTime: 'PlayTime',
  Kids: 'Kids',
  Photos: 'Photos',
  Saved: 'Saved',
  Share: 'Share',
  AccountAndSubscription: 'AccountAndSubscription',
  HelpGuide: 'Help Guide',
  TermsAndConditions: 'Terms & Conditions',
  KidsEdit: 'Kids Edit',
  EarlybirdShop: 'EarlybirdShop',
  ChangePassword: 'ChangePassword',
  EditProfile: 'EditProfile',
  PrivacyPolicy: 'Privacy Policy',
  PdfView: 'PdfView',
  MoreThemes: 'MoreThemes',
};
