import { StyleSheet } from 'react-native';
import { WIN_HEIGHT, WIN_WIDTH } from '../../constants/constant';
import { colors } from '../../styles';
import { doubleIndent, halfindent, indent, lessIndent } from '../../styles/dimensions';
import { scale, scaleVertical } from '../../utils/scale';

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.rootbg,
  },
  scrollContain: {
    backgroundColor: colors.white,
  },
  paddingbt: {
    flex: 1,
    paddingBottom: indent,
  },
  topNav: {},
  imgToplogo: {
    width: '100%',
    height: 84,
    position: 'relative',
  },
  ealrylogo: {
    position: 'absolute',
    alignSelf: 'center',
    top: 32,
  },
  thisMonthWrap: {
    paddingHorizontal: indent,
    marginTop: indent + halfindent,
  },
  monthWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  },
  mbmargin: {
    marginBottom: halfindent + 2,
  },
  monthText: {
    fontFamily: 'Navigo-Medium',
    fontSize: 10,
    letterSpacing: 1.28,
    color: colors.textColor,
    textTransform: 'uppercase',
  },
  viewState: {
    fontFamily: 'Navigo-Regular',
    color: colors.textColor,
    fontSize: 14,
  },
  moreIcon: {
    marginTop: 2,
  },
  firstWrap: {
    flexDirection: 'row',
    marginRight: -indent,
  },
  atCompleted: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    padding: indent - 2,
    flex: 0.5,
    marginRight: indent,
  },
  mpCompleted: {
    backgroundColor: colors.greenBg,
    borderRadius: 8,
    padding: indent - 2,
    flex: 0.5,
    marginRight: indent,
  },
  rightArrowWrap: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  activityNum: {
    fontFamily: 'NewSpirit-Regular',
    color: colors.white,
    fontSize: 38,
    lineHeight: 47,
  },
  rowactivity: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  titlebox: {
    fontFamily: 'Navigo-Regular',
    color: colors.white,
    lineHeight: 17,
    marginTop: 'auto',
  },
  ActivityToday: {
    marginTop: doubleIndent,
    paddingHorizontal: indent,
  },
  todayText: {
    fontFamily: 'NewSpirit-Regular',
    letterSpacing: 0.16,
    color: colors.black,
  },
  wrapCardToday: {
    width: 322,
    marginHorizontal: halfindent,
    //
    paddingBottom: 32,
    paddingTop: lessIndent,
  },
  boxShadow: {
    backgroundColor: colors.transparent,
    borderRadius: 8,
    shadowColor: colors.cardboxshadow,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  todaysWrapper: {
    flexDirection: 'row',
    marginHorizontal: halfindent,
  },
  imgWrapToday: {
    width: '100%',
    height: 228,
    borderRadius: 8,
    overflow: 'hidden',
    position: 'relative',
  },
  imgToday: {
    width: '100%',
    height: 240,
    borderRadius: 8,
  },
  labelWrap: {
    position: 'absolute',
    backgroundColor: colors.white,
    paddingHorizontal: halfindent + 2,
    paddingVertical: halfindent / 2,
    borderRadius: 32,
    right: 9,
    top: 8,
  },
  labelText: {
    fontSize: 8,
    fontFamily: 'Navigo-Medium',
    letterSpacing: 1.6,
    color: colors.black,
  },
  cardWrapToday: {
    paddingHorizontal: indent + halfindent,
    paddingTop: indent,
    paddingBottom: halfindent,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    marginTop: -24,
  },
  todayTitle: {
    fontFamily: 'Navigo-Medium',
    fontSize: 10,
    letterSpacing: 1.6,
    textTransform: 'uppercase',
    color: colors.greyThree,
  },
  titleSkills: {
    fontFamily: 'NewSpirit-Regular',
    color: colors.black,
    marginTop: halfindent / 2,
  },
  tagWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: halfindent,
  },
  wrapLast: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: halfindent,
    flexWrap: 'wrap',
  },
  labelCard: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  labelcard: {
    paddingHorizontal: lessIndent,
    paddingVertical: halfindent / 2,
    borderRadius: 32,
    marginBottom: 4,
  },
  todayTag: {
    fontFamily: 'Navigo-Medium',
    fontSize: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: colors.black,
    textAlign: 'center',
  },
  horizontalscroll: {
    backgroundColor: colors.white,
  },
  earlyQuotes: {
    paddingHorizontal: indent,
    marginBottom: indent,
  },
  earlyCard: {
    backgroundColor: colors.rootbg,
    borderRadius: 8,
    paddingVertical: doubleIndent + halfindent,
    paddingHorizontal: 70,
  },
  logoImg: {
    alignSelf: 'center',
    width: 55,
    height: 55,
    marginBottom: lessIndent,
  },
  earlyText: {
    fontFamily: 'Navigo-Regular',
    textAlign: 'center',
    color: colors.textColor,
    alignSelf: 'center',
    lineHeight: 23,
  },
  milestoneWrap: {
    paddingHorizontal: indent,
    marginTop: halfindent,
  },
  milesText: {
    fontFamily: 'NewSpirit-Regular',
    color: colors.black,
    letterSpacing: 0.16,
  },
  cardList: {
    paddingVertical: lessIndent,
    paddingLeft: lessIndent,
    paddingRight: indent,
    borderRadius: 8,
    marginTop: indent,
    shadowColor: colors.cardboxshadow,
    shadowOffset: {
      width: 0,
      height: 9,
    },
    shadowOpacity: 0.5,
    shadowRadius: 12.35,

    elevation: 19,
  },
  cardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  leftRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileImg: {
    width: 56,
    height: 56,
    borderRadius: 50,
  },
  childName: {
    fontFamily: 'NewSpirit-Regular',
    color: colors.textColor,
    lineHeight: 25,
    letterSpacing: 0.16,
  },
  textWrap: {
    paddingLeft: lessIndent,
  },
  years: {
    fontFamily: 'NewSpirit-Regular',
    color: colors.greylite,
  },
  midfulPlay: {
    marginTop: doubleIndent,
    backgroundColor: colors.linearPurple,
    paddingTop: doubleIndent + indent,
    paddingHorizontal: indent,
    paddingBottom: indent + halfindent,
  },
  birdsImg: {
    width: 113,
    height: 118,
    alignSelf: 'center',
    marginBottom: indent,
  },
  whiteLogo: {
    width: 113,
    height: 113,
    borderRadius: 100,
    alignSelf: 'center',
    backgroundColor: colors.white,
  },
  mindContain: {
    marginTop: indent,
  },
  mindfulText: {
    fontFamily: 'NewSpirit-Regular',
    textAlign: 'center',
    color: colors.textColor,
    marginBottom: lessIndent,
  },
  mindCaps: {
    fontFamily: 'Navigo-Regular',
    color: colors.textColor,
    textAlign: 'center',
    fontSize: 16,
    lineHeight: 26,
    marginBottom: indent,
  },
  btnSpace: {
    // marginTop: indent,
  },
  btnText: {
    fontFamily: 'Navigo-Medium',
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 1.6,
    fontSize: 10,
    color: colors.primary,
    marginTop: indent,
  },
  btmBorder: {
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'center',
    borderColor: colors.primary,
  },
  shareWrap: {
    marginTop: indent + halfindent,
    paddingHorizontal: indent + halfindent,
    marginHorizontal: indent,
    paddingTop: indent,
    backgroundColor: colors.splacebg,
    borderRadius: 8,
    paddingBottom: indent + 3,
    position: 'relative',
  },
  invText: {
    fontFamily: 'NewSpirit-Regular',
    color: colors.primary,
    fontSize: 20,
    lineHeight: 25,
  },
  appCaps: {
    fontFamily: 'Navigo-Regular',
    lineHeight: 20,
    color: colors.textColor,
    marginTop: 3,
  },
  btnWrap: {
    flexDirection: 'row',
    marginTop: lessIndent + 2,
  },
  shareBtn: {
    paddingHorizontal: 15,
    paddingVertical: 6,
    backgroundColor: colors.primary,
    borderRadius: 40,
  },
  shareBtnText: {
    fontFamily: 'Navigo-Medium',
    fontSize: 10,
    lineHeight: 14,
    textTransform: 'uppercase',
    letterSpacing: 1,
    color: colors.white,
  },
  alligator: {
    width: 163,
    height: 81,
    position: 'absolute',
    right: -16,
    bottom: -18,
  },
  shareImg: {
    width: '100%',
    height: 130,
  },
  wrapWorkCard: {
    marginBottom: doubleIndent,
    marginHorizontal: indent,
    backgroundColor: colors.white,
    borderRadius: 8,
    shadowColor: colors.cardboxshadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 18,
  },
  workShopWrap: {},
  imgWrap: {
    width: '100%',
    height: 240,
    borderRadius: 8,
    overflow: 'hidden',
    position: 'relative',
  },
  imgVideo: {
    width: '100%',
    height: 240,
    borderRadius: 8,
  },
  playBtn: {
    width: 48,
    height: 48,
    backgroundColor: colors.blackbtn,
    position: 'absolute',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    top: '35%',
  },
  cardWrap: {
    paddingHorizontal: indent + halfindent,
    paddingVertical: indent,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    marginTop: -24,
  },
  smallTitle: {
    fontFamily: 'Navigo-Medium',
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 1,
    color: colors.greyThree,
    textTransform: 'uppercase',
  },
  titleArticles: {
    fontFamily: 'NewSpirit-Regular',
    color: colors.textColor,
    marginTop: halfindent / 2,
  },
  leftbmborder: {
    borderBottomWidth: 1,
    borderBottomColor: colors.primary,
    alignSelf: 'flex-start',
  },
  linkTag: {
    fontFamily: 'Navigo-Medium',
    fontSize: 10,
    textTransform: 'uppercase',
    color: colors.primary,
    letterSpacing: 1,
    marginTop: halfindent,
  },
  ReadingToday: {
    paddingHorizontal: indent,
    marginBottom: indent,
  },
  WorkingToday: {
    paddingHorizontal: indent,
    marginTop: indent + halfindent + 6,
    marginBottom: indent,
  },
  //mindfulModal
  mindfulModal: {
    width: WIN_WIDTH - indent * 3,
    height: 'auto',
    backgroundColor: colors.rootbg,
    borderRadius: 8,
  },
  // mindModal: {
  //   flex: 1,
  //   backgroundColor:colors.t
  // },
  mindfulImg: {
    width: 154,
    height: 154,
    alignSelf: 'center',
  },
  titlemodalText: {
    fontFamily: 'NewSpirit-Regular',
    textAlign: 'center',
    letterSpacing: 0.3,
    color: colors.textColor,
    marginTop: halfindent,
  },
  modalCaps: {
    fontFamily: 'Navigo-Regular',
    textAlign: 'center',
    fontSize: 10,
    color: colors.textColor,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginTop: halfindent,
  },
  modalRoot: {
    paddingVertical: doubleIndent,
  },
  btnModalWrap: {
    paddingHorizontal: doubleIndent * 2 + 6,
    paddingTop: doubleIndent,
    paddingBottom: indent + 10,
  },
  closeIcon: {
    position: 'absolute',
    width: 40,
    height: 40,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
    right: 16,
    top: 16,
  },
  //InfoModal
  modal: {
    backgroundColor: colors.transparent,
    flex: 1,
    justifyContent: 'flex-end',
  },
  keyBord: {
    flex: 1,
  },
  modalWrapper: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.transparent,
  },
  closeModal: {
    flex: 1,
  },
  rectView: {
    width: 50,
    height: 5,
    alignSelf: 'center',
    backgroundColor: colors.backgroundColor,
    opacity: 0.8,
    borderRadius: 25,
    marginBottom: scaleVertical(8),
  },
  modalBox: {
    paddingHorizontal: indent,
    justifyContent: 'flex-end',
    backgroundColor: colors.white,
    borderTopLeftRadius: lessIndent,
    borderTopRightRadius: lessIndent,
    position: 'relative',
    maxHeight: WIN_HEIGHT - scale(85),
  },
  paddingModal: {
    paddingVertical: indent,
  },
  playTimeText: {
    fontFamily: 'NewSpirit-Regular',
    textAlign: 'center',
    letterSpacing: 0.16,
    color: colors.textColor,
  },
  spendTime: {
    marginVertical: indent + halfindent,
  },
  spendCaption: {
    fontFamily: 'Navigo-Regular',
    textAlign: 'center',
    color: colors.textColor,
    lineHeight: 19,
  },
  playTimeCard: {
    backgroundColor: colors.rootbg,
    padding: indent + 4,
    borderRadius: 8,
    marginBottom: doubleIndent,
  },
  cardTitle: {
    fontFamily: 'NewSpirit-Regular',
    color: colors.black,
    marginBottom: halfindent / 2,
  },
  listRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: lessIndent,
  },
  listText: {
    fontFamily: 'Navigo-Regular',
    color: colors.black,
    marginLeft: halfindent,
  },
  blogCaps: {
    marginBottom: doubleIndent,
  },
  blogText: {
    color: colors.textColor,
    fontFamily: 'Navigo-Regular',
    lineHeight: 19,
  },
  selectIcon: {
    position: 'absolute',
    left: 8,
    top: 8,
  },
});
